# See https://github.com/NixOS/nixpkgs/issues/121694#issuecomment-2159420924
# paste to /etc/sysctl.d/60-apparmor-namespace.conf
 kernel.apparmor_restrict_unprivileged_userns=0
# then apply changes sudo sysctl --system
